### PR TITLE
Create a database based on a diagram

### PR DESCRIPTION
**Pull request by kinginthenorthcodez**
## Create a database based on a diagram 👍🏽 
- Create a file named schema_based_on_diagram.sql where you implement the database from the diagram.
- might not appear in the diagram, but you still need Join tables from many-to-many relationships d them
- Remember to add the FK indexes.
Warm Regards

@kinginthenorthcodez 
@gedewon

### CODE REVIEW

**Review by Whoistolu — COMMENTED** [review]
Hi Team,
@kinginthenorthcodez

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has an empty file. The new tables should be created in the `schema_based_on_diagram.sql` file. You created the file but seem to have forgotten to add the necessary code to the file.
- Also, kindly ensure that there are equal commits on this milestone as it is pair program based(Teamwork). Currently, only one person has pushed a commit for this submission.
 Please fix this and ask for another submission.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by kinginthenorthcodez** [comment]
@Whoistolu  sorry the empty file has been fixed  and yes we did pair program just that we agreed I do the driving in this task as he did in the previous task

**Review by mmsesay — APPROVED** [review]
Hi @kinginthenorthcodez & @Gedewon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - Good Readme :heavy_check_mark:
 - Good PR title & summary :heavy_check_mark: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kinginthenorthcodez** [comment]
Merged #6  into development

**Pull request merged**
